### ISSUE TITLE
Release with Middleware?

### ISSUE THREAD

**Issue by Zoramite** [LeadPages/wdio-static-server-service#5]
Are there plans to make a npm release with middleware support? It seems to be in the codebase, but not in the latest npm version?

**Comment by birdy-** [comment]
Yes it would be great to release a version with middleware

**Comment by Zoramite** [comment]
This doesn't seem to work with the renamed package. The webdriver service import is looking for the normal https://www.npmjs.com/package/wdio-static-server-service package and doesn't find it since it is in the `@saucylabs/wdio-static-server-service`.

```
ERROR: Couldn't initialise service "static-server".
Error: Cannot find module 'wdio-static-server-service'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Runner.initialiseServices (node_modules/webdriverio/build/lib/runner.js:689:35)
    ...
```

**Comment by Zoramite** [comment]
@nrdobie is it possible to release to the original pack name with the latest merged changes?

**Comment by christian-bromann** [comment]
@Zoramite you need to require it first and then add it do the list (it's a bug and will be fixed soon), try:
```js
var StaticServerService = require('@saucelabs/wdio-static-server-service');
export.config = {
  // ...
  services: [StaticServerService],
  // ...
}
```

**Comment by bludot** [comment]
the problem here is also npm updated. `prepublish` is now `prepare`
